//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pl_PL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pl_PL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp2.lang.pl-PL", typeof(pl_PL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść graf.
        /// </summary>
        internal static string BtnClearGraphText {
            get {
                return ResourceManager.GetString("BtnClearGraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolor.
        /// </summary>
        internal static string BtnColorChoiceText {
            get {
                return ResourceManager.GetString("BtnColorChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń wierzchołek.
        /// </summary>
        internal static string BtnDeleteVertexText {
            get {
                return ResourceManager.GetString("BtnDeleteVertexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angielski.
        /// </summary>
        internal static string BtnLangEnglishText {
            get {
                return ResourceManager.GetString("BtnLangEnglishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski.
        /// </summary>
        internal static string BtnLangPolishText {
            get {
                return ResourceManager.GetString("BtnLangPolishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wczytaj.
        /// </summary>
        internal static string BtnLoadText {
            get {
                return ResourceManager.GetString("BtnLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string BtnSaveText {
            get {
                return ResourceManager.GetString("BtnSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import/Eksport.
        /// </summary>
        internal static string groupBox1Text {
            get {
                return ResourceManager.GetString("groupBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja.
        /// </summary>
        internal static string groupBox2Text {
            get {
                return ResourceManager.GetString("groupBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język.
        /// </summary>
        internal static string groupBox3Text {
            get {
                return ResourceManager.GetString("groupBox3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graf wczytano pomyślnie..
        /// </summary>
        internal static string loadedText {
            get {
                return ResourceManager.GetString("loadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd pliku..
        /// </summary>
        internal static string loadFailedText {
            get {
                return ResourceManager.GetString("loadFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graf zapisano pomyślnie..
        /// </summary>
        internal static string savedText {
            get {
                return ResourceManager.GetString("savedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytor grafów.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
